### ISSUE TITLE
Initial layout Index Page 2

### ISSUE THREAD

**Issue by cortcortx** [cortcortx/24-06-JavaScriptProject-Team1#3]
On index.html layout page
-header `<head>`
-bootstrap link `<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">`

_Header_ `<header>`
- [x]  Make Pixel Pals text stand out using <h1> with id #main_title_text

_Main content_ `<main>`
main content has 2 sections:
- [x] form (left section) with id `#pet_form`
- [x] left section id => `left section`
- [x] cards container (right section)` <div>` with id `#pets_container`

_Left section_(form: `#create_pet_form`):
- [x] create `<label>` and `<select>` dropdown input field with the id` #pet_species` for both
- [x] nested inside the select, create 4 `<option>` elements with the following values: "cat" "dog" "gorilla" "turtle"

- [x] create `<label>` and `<input> ` field with type="text", placeholder="Choose a name",  id `#pet_name` for both

- [x] create `<label>` and `<select>` dropdown input field with the id` #pet_gender` for both
- [x] nested inside the select, create 3 `<option>` elements with the following values: "male" "female" "unknown"

- [x] create `<label>` and `<select>` dropdown input field with the id` #pet_personality` for both
- [x] nested inside the select, create 5 `<option>` elements with the following values: "kind" "goofy" "intelligent" "stubborn" "timid"

- [x] create `<label>` and `<select>` dropdown input field with the id` #pet_habitat` for both
- [x] nested inside the select, create 4 `<option>` elements with the following values: "city" "forest" "desert" "river"

- [x] create a `<button>` element with the type="submit" and id `#submit_btn`

**Comment by planeJayne** [comment]
I added the Pixel Pals header but I have not styled yet.
@cortcortx @Olutobi9698
